name = "test"
type = "javascript"
workers_dev = true
compatibility_date = "2024-03-20"
compatibility_flags = ["python_workers"]

[site]
bucket = "./dist"
entry-point = "."

[build]
command = "mesop build"


